site_name: Carlos Batista
markdown_extensions:
  - tables
  - admonition
  - pymdownx.details
  - toc:
      permalink: false
theme:
  name: material
  language: pt-BR
  palette:
    scheme: slate  
    primary: deep purple
  features:
    - header.autohide
    - navigation.path
    - navigation.indexes
    - navigation.prune
  custom_dir: overrides
plugins:
  - search  